openapi: 3.0.0
info:
  title: Simple File and Folder API
  version: 1.0.0
  description: An API for managing folders and files

paths:
  /folders:
    get:
      summary: List all folders
      responses:
        '200':
          description: A list of folders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Folder'
    post:
      summary: Create a new folder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Folder'
      responses:
        '201':
          description: Successfully created a new folder
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Folder'
    # Add PUT and DELETE operations here

  /files:
    get:
      summary: List all files
      responses:
        '200':
          description: A list of files
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/File'
    post:
      summary: Create a new file
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/File'
      responses:
        '201':
          description: Successfully created a new file
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/File'
    # Add PUT and DELETE operations here

components:
  schemas:
    Folder:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the folder
        name:
          type: string
          description: Name of the folder
      required:
        - id
        - name

    File:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the file
        name:
          type: string
          description: Name of the file
        folderId:
          type: string
          description: Identifier of the folder the file belongs to
      required:
        - id
        - name
        - folderId
